name: Build Debian Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Debian Package
        run: dpkg-deb --build nopasswd

      - name: Verify Package Version
        run: |
          version=$(dpkg-deb --field nopasswd.deb Version)
          tag_version=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
          if [ "$version" != "$tag_version" ]; then
            echo "Error: Package version ($version) does not match tag version ($tag_version)"
            exit 1
          fi

      - name: Rename Debian Package
        run: dpkg-name nopasswd.deb

      - name: Determine Renamed Package Name
        id: extract_filename
        run: echo "::set-output name=filename::$(find nopasswd_*)"

