name: Build and Release Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Debian Package
        run: dpkg-deb --build nopasswd

      - name: Rename Debian Package
        run: dpkg-name nopasswd.deb

      - name: Determine Renamed Package Name
        id: extract_filename
        run: echo "::set-output name=filename::$(find nopasswd_*)"

      - name: Upload Built Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_filename.outputs.filename }}
          path: ${{ steps.extract_filename.outputs.filename }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.check_version.outputs.version }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.extract_filename.outputs.filename }}
          asset_name: ${{ steps.extract_filename.outputs.filename }}
          asset_content_type: application/octet-stream

