name: Build and Release Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Debian Package
        run: dpkg-deb --root-owner-group --build nopasswd

      - name: Verify Version
        if: startsWith(github.ref, 'refs/tags/v')
        id: check_version
        run: |
          version=$(dpkg-deb --field nopasswd.deb Version)
          if [[ ! "${{ github.ref }}" == "ref/tag/v${version}" ]]; then
            echo "Error: Package version ($version) does not match tag version ($tag_version)"
            exit 1
          fi
          echo "::set-output name=version::$version"

      - name: Rename Package
        run: dpkg-name nopasswd.deb

      - name: Determine Package Name
        id: extract_filename
        run: echo "::set-output name=filename::$(find nopasswd_*)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.extract_filename.outputs.filename }}
          path: ${{ steps.extract_filename.outputs.filename }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.extract_filename.outputs.filename }} 
          draft: true

